version: "3"
services:
  linx:
    container_name: linx-server
    image: andreimarcu/linx-server
    command: -config /data/linx-server.conf
    volumes:
      - data:/data
    restart: unless-stopped
    ports:
      - "10668:8080"
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.linx.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.linx.entrypoints=websecure"
      - "traefik.http.routers.linx.tls=true"
volumes:
  data:
networks:
  traefik_default:
    external: true
