version: "3"
services:
  app:
    image: vaultwarden/server:1.32.1
    restart: always
    volumes:
      - data:/data
    environment:
      - DOMAIN=https://${APP_URL}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SHOW_PASSWORD_HINT=${SHOW_PASSWORD_HINT}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURITY=${SMTP_SECURITY}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.bitwarden.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.bitwarden.entrypoints=websecure"
      - "traefik.http.routers.bitwarden.tls=true"
    networks:
      - traefik_default
volumes:
  data:
networks:
  traefik_default:
    external: true
