version: "3"
services:
  app:
    image: lscr.io/linuxserver/bookstack
#    image: solidnerd/bookstack:21.12.1
    ports:
      - ${APP_PORT}:80
    restart: always
    volumes:
      - data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://${APP_URL}
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.bookstack.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.bookstack.entrypoints=websecure"
      - "traefik.http.routers.bookstack.tls=true"
#      - "traefik.http.services.bookstack.loadbalancer.server.port=${APP_PORT}"
    networks:
      - default
      - traefik_default
    depends_on:
      - db
  db:
    image: lscr.io/linuxserver/mariadb
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=${DB_ROOT}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - db:/config
    networks:
      - default
volumes:
  data:
  db:
networks:
  default:
  traefik_default:
    external: true
