version: '3'
services:
  server:
    image: stilliard/pure-ftpd
    container_name: ftp-standalone
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      FTP_USER_NAME: ${FTP_USER_NAME}
      FTP_USER_PASS: ${FTP_USER_PASS}
      FTP_USER_HOME: /home/ftp/
    restart: always
