version: "2.1"
services:
  transmission:
    image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${APP_TIMEZONE}
      - TRANSMISSION_WEB_HOME=/kettu/
    volumes:
      - config:/config
      - downloads:/downloads
      - watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.transmission.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls=true"
      - "traefik.http.routers.transmission.middlewares=auth-default"
    networks:
      - traefik_default
  nginx:
    image: nginx:stable
    volumes:
      - ./download.conf:/etc/nginx/conf.d/download.conf
      - downloads:/var/www/downloads:ro
    ports:
      - 9092:80
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.transmission-downloads.rule=Host(`${DOWNLOAD_URL}`)"
      - "traefik.http.routers.transmission-downloads.entrypoints=websecure"
      - "traefik.http.routers.transmission-downloads.tls=true"
      - "traefik.http.routers.transmission-downloads.middlewares=ipwhitelist-local"
    networks:
      - traefik_default
volumes:
  config:
  downloads:
  watch:
networks:
  traefik_default:
    external: true
